server:
  port: 8686

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            #当前数据源操作类型
    #driver-class-name: com.mysql.cj.jdbc.Driver           # mysql驱动
    driver-class-name: com.mysql.jdbc.Driver           # mysql驱动
    url: jdbc:mysql://106.14.28.54:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234

    #json序列化配置
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    jmx:
      enabled: false

  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 106.14.28.54 # Redis服务器地址
    port: 6379 # Redis服务器端口
    password: shixianheng # Redis服务器连接密码（默认为空）
    timeout: 1000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

  rabbitmq:
    host: 106.14.28.54
    port: 5672
    username: user_sxh
    password: 1641352417

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: top.sxh427.mall.entities    # 所有Entity类所在包
